"""Type stubs for the Rust extension module."""

from typing import List, Optional, Sequence, Tuple

__version__: str

class Graph:
    def __init__(self, num_nodes: int, edges: Sequence[Tuple[int, int, int]]) -> None: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    def edge(self, edge: int) -> Tuple[int, int, int]: ...
    def input_index(self, edge: int) -> int: ...
    def out_edges(self, node: int) -> List[int]: ...
    def out_degree(self, node: int) -> int: ...
    def neighbors(self, node: int) -> List[Tuple[int, int, int]]: ...
    def edges(self) -> List[Tuple[int, int, int]]: ...
    def walk(self, start: int, edges: Sequence[int]) -> Tuple[int, int]: ...
    def __len__(self) -> int: ...

class Heuristic:
    @staticmethod
    def zero() -> Heuristic: ...
    @staticmethod
    def euclidean(
        xs: Sequence[float], ys: Sequence[float], cost_per_distance: float
    ) -> Heuristic: ...
    @staticmethod
    def landmarks(
        graph: Graph, count: int, selection: str = ..., seed: int = ...
    ) -> Heuristic: ...
    @property
    def coverage(self) -> Optional[int]: ...
    @property
    def footprint(self) -> int: ...
    def estimate(self, node: int, target: int) -> int: ...

class OsmNetwork:
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def node_ids(self) -> List[int]: ...
    @property
    def bounds(self) -> Tuple[float, float, float, float]: ...
    def edges(self) -> List[Tuple[int, int, int]]: ...
    def projected(self) -> Tuple[List[float], List[float]]: ...
    def coordinates(self) -> Tuple[List[float], List[float]]: ...
    def geometry(self, edge: int) -> List[Tuple[float, float]]: ...
    def nearest(
        self, lat: float, lon: float, within: Optional[Sequence[int]] = ...
    ) -> Optional[int]: ...

class SearchResult:
    @property
    def costs(self) -> List[Optional[int]]: ...
    @property
    def order(self) -> List[int]: ...
    def cost(self, node: int) -> Optional[int]: ...
    def path(self, node: int) -> Optional[List[int]]: ...
    def edge_path(self, node: int) -> Optional[List[int]]: ...
    def parent(self, node: int) -> Optional[int]: ...
    def parent_edge(self, node: int) -> Optional[int]: ...
    def reached(self) -> List[int]: ...
    def tree(self, graph: Graph, magnitude: str = ...) -> SearchTree: ...

class SearchTree:
    @property
    def tails(self) -> List[int]: ...
    @property
    def heads(self) -> List[int]: ...
    @property
    def edges(self) -> List[int]: ...
    @property
    def magnitudes(self) -> List[int]: ...
    @property
    def peak(self) -> int: ...
    def __len__(self) -> int: ...

def astar(
    graph: Graph,
    sources: Sequence[Tuple[int, int]],
    target: int,
    heuristic: Heuristic,
    *,
    max_cost: Optional[int] = ...,
) -> SearchResult: ...
def load_osm(
    path: str,
    speeds: Sequence[Tuple[str, float]],
    *,
    respect_oneway: bool = ...,
    use_maxspeed: bool = ...,
) -> OsmNetwork: ...
def dijkstra(
    graph: Graph,
    sources: Sequence[Tuple[int, int]],
    *,
    targets: Optional[Sequence[int]] = ...,
    max_cost: Optional[int] = ...,
) -> SearchResult: ...
def bfs(
    graph: Graph,
    sources: Sequence[int],
    *,
    targets: Optional[Sequence[int]] = ...,
    max_depth: Optional[int] = ...,
) -> SearchResult: ...
