"""Type stubs for the Rust extension module."""

from typing import List, Optional, Sequence, Tuple

__version__: str

class Graph:
    def __init__(self, num_nodes: int, edges: Sequence[Tuple[int, int, int]]) -> None: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    def edge(self, edge: int) -> Tuple[int, int, int]: ...
    def input_index(self, edge: int) -> int: ...
    def out_edges(self, node: int) -> List[int]: ...
    def out_degree(self, node: int) -> int: ...
    def neighbors(self, node: int) -> List[Tuple[int, int, int]]: ...
    def edges(self) -> List[Tuple[int, int, int]]: ...
    def reversed(self) -> Graph: ...
    def walk(self, start: int, edges: Sequence[int]) -> Tuple[int, int]: ...
    def __len__(self) -> int: ...

class Calendar:
    @staticmethod
    def from_windows(
        graph: Graph, windows: Sequence[Tuple[int, Sequence[Tuple[int, int]]]]
    ) -> Calendar: ...
    @staticmethod
    def unrestricted() -> Calendar: ...
    @property
    def footprint(self) -> int: ...
    def is_open(self, edge: int, at: int) -> bool: ...
    def is_restricted(self, edge: int) -> bool: ...
    def __len__(self) -> int: ...

class Feed:
    @property
    def stop_ids(self) -> List[str]: ...
    @property
    def stop_names(self) -> List[str]: ...
    @property
    def num_stops(self) -> int: ...
    @property
    def num_connections(self) -> int: ...
    @property
    def unimplemented(self) -> int: ...
    @property
    def trips_not_running(self) -> int: ...
    def coordinates(self) -> Tuple[List[float], List[float]]: ...
    def trips(self) -> Tuple[List[str], List[str]]: ...
    def edges(self) -> List[Tuple[int, int, int]]: ...
    def connections(self, index: int) -> List[Tuple[int, int, int]]: ...

class Timetable:
    @staticmethod
    def from_connections(
        graph: Graph, connections: Sequence[Tuple[int, Sequence[Tuple[int, int, int]]]]
    ) -> Timetable: ...
    @property
    def num_stops(self) -> int: ...
    @property
    def num_connections(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def earliest_arrival(self, from_: int, at: int, to: int) -> Optional[Itinerary]: ...

class TimeExpanded:
    @staticmethod
    def build(timetable: Timetable) -> TimeExpanded: ...
    @property
    def num_events(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def earliest_arrival(self, from_: int, at: int, to: int) -> Optional[Itinerary]: ...

class Itinerary:
    @property
    def arrives(self) -> int: ...
    @property
    def settled(self) -> int: ...
    @property
    def transfers(self) -> int: ...
    def rides(self) -> List[Tuple[int, int, int, int, int]]: ...

class ContractionHierarchy:
    @staticmethod
    def edge_difference(
        graph: Graph,
        deleted_neighbours: bool = ...,
        max_settled: int = ...,
        max_hops: int = ...,
    ) -> ContractionHierarchy: ...
    @staticmethod
    def random(
        graph: Graph,
        seed: int = ...,
        max_settled: int = ...,
        max_hops: int = ...,
    ) -> ContractionHierarchy: ...
    @property
    def num_shortcuts(self) -> int: ...
    @property
    def num_arcs(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    @property
    def ranks(self) -> List[int]: ...
    def query(
        self, sources: Sequence[Tuple[int, int]], target: int
    ) -> MeetingSearch: ...

class MeetingSearch:
    @property
    def meeting(self) -> Optional[int]: ...
    @property
    def settled(self) -> int: ...
    @property
    def halves(self) -> Tuple[List[int], List[int]]: ...
    def cost(self, node: int) -> Optional[int]: ...
    def path(self, node: int) -> Optional[List[int]]: ...
    def edge_path(self, node: int) -> Optional[List[int]]: ...
    def branches(self) -> List[Tuple[int, int, int, int, List[int]]]: ...

class Heuristic:
    @staticmethod
    def zero() -> Heuristic: ...
    @staticmethod
    def euclidean(
        xs: Sequence[float], ys: Sequence[float], cost_per_distance: float
    ) -> Heuristic: ...
    @staticmethod
    def landmarks(
        graph: Graph, count: int, selection: str = ..., seed: int = ...
    ) -> Heuristic: ...
    @property
    def coverage(self) -> Optional[int]: ...
    @property
    def footprint(self) -> int: ...
    def estimate(self, node: int, target: int) -> int: ...

class OsmNetwork:
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def node_ids(self) -> List[int]: ...
    @property
    def bounds(self) -> Tuple[float, float, float, float]: ...
    def edges(self) -> List[Tuple[int, int, int]]: ...
    def projected(self) -> Tuple[List[float], List[float]]: ...
    def coordinates(self) -> Tuple[List[float], List[float]]: ...
    def geometry(self, edge: int) -> List[Tuple[float, float]]: ...
    def windows(self) -> List[Tuple[int, List[Tuple[int, int]]]]: ...
    @property
    def unreadable_schedules(self) -> int: ...
    def nearest(
        self, lat: float, lon: float, within: Optional[Sequence[int]] = ...
    ) -> Optional[int]: ...

class SearchResult:
    @property
    def costs(self) -> List[Optional[int]]: ...
    @property
    def order(self) -> List[int]: ...
    @property
    def settled(self) -> int: ...
    def cost(self, node: int) -> Optional[int]: ...
    def path(self, node: int) -> Optional[List[int]]: ...
    def edge_path(self, node: int) -> Optional[List[int]]: ...
    def parent(self, node: int) -> Optional[int]: ...
    def parent_edge(self, node: int) -> Optional[int]: ...
    def reached(self) -> List[int]: ...
    def tree(self, graph: Graph, magnitude: str = ...) -> SearchTree: ...

class SearchTree:
    @property
    def tails(self) -> List[int]: ...
    @property
    def heads(self) -> List[int]: ...
    @property
    def edges(self) -> List[int]: ...
    @property
    def magnitudes(self) -> List[int]: ...
    @property
    def peak(self) -> int: ...
    def __len__(self) -> int: ...

def astar(
    graph: Graph,
    sources: Sequence[Tuple[int, int]],
    target: int,
    heuristic: Heuristic,
    *,
    max_cost: Optional[int] = ...,
) -> SearchResult: ...
def load_gtfs(path: str, year: int, month: int, day: int) -> Feed: ...
def load_osm(
    path: str,
    speeds: Sequence[Tuple[str, float]],
    *,
    respect_oneway: bool = ...,
    use_maxspeed: bool = ...,
    access_keys: Sequence[str] = ...,
) -> OsmNetwork: ...
def time_dependent_dijkstra(
    graph: Graph,
    calendar: Calendar,
    sources: Sequence[Tuple[int, int]],
    departing: int,
    *,
    waiting: str = ...,
    targets: Optional[Sequence[int]] = ...,
    max_cost: Optional[int] = ...,
) -> SearchResult: ...
def dijkstra(
    graph: Graph,
    sources: Sequence[Tuple[int, int]],
    *,
    targets: Optional[Sequence[int]] = ...,
    max_cost: Optional[int] = ...,
) -> SearchResult: ...
def bfs(
    graph: Graph,
    sources: Sequence[int],
    *,
    targets: Optional[Sequence[int]] = ...,
    max_depth: Optional[int] = ...,
) -> SearchResult: ...
