"""Type stubs for the Rust extension module."""

from typing import List, Optional, Sequence, Tuple

__version__: str

class Graph:
    def __init__(self, num_nodes: int, edges: Sequence[Tuple[int, int, int]]) -> None: ...
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    def edge(self, edge: int) -> Tuple[int, int, int]: ...
    def input_index(self, edge: int) -> int: ...
    def out_edges(self, node: int) -> List[int]: ...
    def out_degree(self, node: int) -> int: ...
    def neighbors(self, node: int) -> List[Tuple[int, int, int]]: ...
    def edges(self) -> List[Tuple[int, int, int]]: ...
    def reversed(self) -> Graph: ...
    def walk(self, start: int, edges: Sequence[int]) -> Tuple[int, int]: ...
    def __len__(self) -> int: ...

class Calendar:
    @staticmethod
    def from_windows(
        graph: Graph, windows: Sequence[Tuple[int, Sequence[Tuple[int, int]]]]
    ) -> Calendar: ...
    @staticmethod
    def unrestricted() -> Calendar: ...
    @property
    def footprint(self) -> int: ...
    def is_open(self, edge: int, at: int) -> bool: ...
    def is_restricted(self, edge: int) -> bool: ...
    def __len__(self) -> int: ...

class Progress:
    def __init__(self) -> None: ...
    def read(self) -> Tuple[str, int, int]: ...
    @property
    def phase(self) -> str: ...
    @property
    def fraction(self) -> Optional[float]: ...

class Feed:
    @property
    def stop_ids(self) -> List[str]: ...
    @property
    def stop_names(self) -> List[str]: ...
    @property
    def num_stops(self) -> int: ...
    @property
    def num_connections(self) -> int: ...
    @property
    def unimplemented(self) -> int: ...
    @property
    def trips_not_running(self) -> int: ...
    def coordinates(self) -> Tuple[List[float], List[float]]: ...
    def trips(self) -> Tuple[List[str], List[str]]: ...
    def edges(self) -> List[Tuple[int, int, int]]: ...
    def connections(self, index: int) -> List[Tuple[int, int, int]]: ...

EARTH_RADIUS: float

def haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float: ...

class Modes:
    def __init__(
        self,
        states: int,
        symbols: int,
        transitions: Sequence[Tuple[int, int, int]],
        starting: Sequence[int],
        accepting: Sequence[int],
    ) -> None: ...
    @property
    def num_states(self) -> int: ...
    @property
    def num_symbols(self) -> int: ...
    @property
    def is_empty(self) -> bool: ...

class Multimodal:
    def __init__(
        self, graph: Graph, labels: bytes, timetable: Timetable, riding: int
    ) -> None: ...
    def earliest_arrival(
        self, modes: Modes, sources: Sequence[Tuple[int, int]], target: int
    ) -> Optional[Itinerary]: ...
    @property
    def num_arcs(self) -> int: ...
    @property
    def footprint(self) -> int: ...

class Ucch:
    @staticmethod
    def build(
        graph: Graph,
        labels: bytes,
        walking: int,
        link_label: int,
        served: Sequence[int],
        max_degree: float = ...,
        progress: Optional[Progress] = ...,
    ) -> Ucch: ...
    def earliest_arrival(
        self,
        network: Multimodal,
        modes: Modes,
        sources: Sequence[Tuple[int, int]],
        target: int,
    ) -> Optional[Itinerary]: ...
    @property
    def num_core(self) -> int: ...
    @property
    def num_arcs(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def is_core(self, node: int) -> bool: ...

class Footpaths:
    @staticmethod
    def from_edges(graph: Graph, positions: Sequence[int]) -> Footpaths: ...
    @staticmethod
    def none() -> Footpaths: ...
    def duration(self, from_: int, to: int) -> Optional[int]: ...
    def __len__(self) -> int: ...
    @property
    def footprint(self) -> int: ...

class Timetable:
    @staticmethod
    def from_connections(
        graph: Graph, connections: Sequence[Tuple[int, Sequence[Tuple[int, int, int]]]]
    ) -> Timetable: ...
    @property
    def num_stops(self) -> int: ...
    @property
    def num_connections(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def earliest_arrival(
        self, sources: Sequence[Tuple[int, int]], to: int, footpaths: Optional[Footpaths] = None
    ) -> Optional[Itinerary]: ...

class TimeExpanded:
    @staticmethod
    def build(timetable: Timetable, footpaths: Optional[Footpaths] = None) -> TimeExpanded: ...
    @property
    def num_events(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def earliest_arrival(self, sources: Sequence[Tuple[int, int]], to: int) -> Optional[Itinerary]: ...

class Raptor:
    @staticmethod
    def build(timetable: Timetable, footpaths: Optional[Footpaths] = None) -> Raptor: ...
    @property
    def num_stops(self) -> int: ...
    @property
    def num_routes(self) -> int: ...
    @property
    def num_trips(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def search(
        self,
        sources: Sequence[Tuple[int, int]],
        *,
        target: Optional[int] = None,
        max_rounds: Optional[int] = None,
        departing: Optional[int] = None,
    ) -> RaptorSearch: ...

class RaptorSearch:
    @property
    def settled(self) -> int: ...
    @property
    def scanned(self) -> int: ...
    @property
    def rounds(self) -> int: ...
    @property
    def departing(self) -> int: ...
    def cost(self, stop: int) -> Optional[int]: ...
    def round_reached(self, stop: int) -> Optional[int]: ...
    def reached(self) -> List[Tuple[int, int, int]]: ...
    def path(self, stop: int) -> Optional[List[int]]: ...
    def itinerary(self, stop: int) -> Optional[Itinerary]: ...
    def itineraries(self, stop: int) -> List[Itinerary]: ...

class ConnectionScan:
    @staticmethod
    def build(timetable: Timetable, footpaths: Optional[Footpaths] = None) -> ConnectionScan: ...
    @property
    def num_stops(self) -> int: ...
    @property
    def num_trips(self) -> int: ...
    @property
    def num_connections(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def search(
        self,
        sources: Sequence[Tuple[int, int]],
        *,
        target: Optional[int] = None,
        departing: Optional[int] = None,
    ) -> ScanSearch: ...
    def profile(self, target: int, departing: int, prune: Optional[int] = None) -> ScanProfile: ...

class ScanSearch:
    @property
    def settled(self) -> int: ...
    @property
    def scanned(self) -> int: ...
    @property
    def departing(self) -> int: ...
    def cost(self, stop: int) -> Optional[int]: ...
    def reached(self) -> List[Tuple[int, int]]: ...
    def path(self, stop: int) -> Optional[List[int]]: ...
    def itinerary(self, stop: int) -> Optional[Itinerary]: ...

class ScanProfile:
    @property
    def settled(self) -> int: ...
    @property
    def scanned(self) -> int: ...
    @property
    def target(self) -> int: ...
    def walk(self, stop: int) -> Optional[int]: ...
    def pairs(self, stop: int, departing: int, until: int) -> List[Tuple[int, int]]: ...
    def journeys(self, stop: int, departing: int, until: int) -> List[Tuple[int, Itinerary]]: ...

class TripBased:
    @staticmethod
    def build(
        timetable: Timetable,
        footpaths: Optional[Footpaths] = None,
        reduce: bool = True,
        progress: Optional[Progress] = None,
    ) -> TripBased: ...
    @property
    def num_stops(self) -> int: ...
    @property
    def num_lines(self) -> int: ...
    @property
    def num_trips(self) -> int: ...
    @property
    def num_transfers(self) -> int: ...
    @property
    def num_initial_transfers(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def search(
        self,
        sources: Sequence[Tuple[int, int]],
        target: int,
        *,
        max_transfers: Optional[int] = None,
        departing: Optional[int] = None,
    ) -> TripBasedSearch: ...
    def profile(self, source: int, target: int, departing: int, until: int) -> TripBasedProfile: ...

class TripBasedSearch:
    @property
    def settled(self) -> int: ...
    @property
    def scanned(self) -> int: ...
    @property
    def departing(self) -> int: ...
    @property
    def target(self) -> int: ...
    @property
    def rounds(self) -> int: ...
    def cost(self, stop: int) -> Optional[int]: ...
    def reached(self) -> List[Tuple[int, int, List[int]]]: ...
    def path(self, stop: int) -> Optional[List[int]]: ...
    def itinerary(self, stop: int) -> Optional[Itinerary]: ...
    def itineraries(self, stop: int) -> List[Itinerary]: ...

class TripBasedProfile:
    @property
    def settled(self) -> int: ...
    @property
    def scanned(self) -> int: ...
    @property
    def runs(self) -> int: ...
    @property
    def source(self) -> int: ...
    @property
    def target(self) -> int: ...
    def walk(self) -> Optional[int]: ...
    def triples(self) -> List[Tuple[int, int, int]]: ...
    def journeys(self) -> List[Tuple[int, Itinerary]]: ...
    def __len__(self) -> int: ...

class PublicTransitLabeling:
    @staticmethod
    def build(
        timetable: Timetable,
        footpaths: Optional[Footpaths] = None,
        progress: Optional[Progress] = None,
    ) -> PublicTransitLabeling: ...
    @property
    def num_stops(self) -> int: ...
    @property
    def num_events(self) -> int: ...
    @property
    def num_hubs(self) -> int: ...
    @property
    def hubs_per_label(self) -> float: ...
    @property
    def footprint(self) -> int: ...
    def earliest_arrival(self, sources: Sequence[Tuple[int, int]], to: int) -> Optional[Itinerary]: ...
    def profile(self, origin: int, target: int, departing: int, until: int) -> List[Tuple[int, Itinerary]]: ...

class Itinerary:
    @property
    def arrives(self) -> int: ...
    @property
    def settled(self) -> int: ...
    @property
    def transfers(self) -> int: ...
    def rides(self) -> List[Tuple[int, int, int, int, int]]: ...
    def legs(self) -> List[Tuple[Optional[int], int, int, int, int]]: ...

class Ultra:
    @staticmethod
    def compute(
        timetable: Timetable, transfers: Graph, progress: Optional[Progress] = ...
    ) -> Ultra: ...
    @property
    def num_shortcuts(self) -> int: ...
    @property
    def candidates(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def shortcuts(self) -> List[Tuple[int, int, int]]: ...
    def footpaths(self) -> Footpaths: ...
    def __len__(self) -> int: ...

class Endpoints:
    """The walks at either end of a journey, and the direct walk they beat."""

    @property
    def direct(self) -> Optional[int]: ...
    @property
    def to_stops(self) -> List[Tuple[int, int]]: ...
    @property
    def from_stops(self) -> List[Tuple[int, int]]: ...

class Buckets:
    """Bucket-CH over a transfer graph: ULTRA's initial and final transfers."""

    @staticmethod
    def build(
        graph: Graph, stops: List[int], progress: Optional[Progress] = ...
    ) -> Buckets: ...
    def endpoints(self, sources: List[Tuple[int, int]], target: int) -> Endpoints: ...
    def path(
        self, sources: List[Tuple[int, int]], to: int
    ) -> Optional[Tuple[int, List[int]]]: ...
    @property
    def num_entries(self) -> int: ...
    @property
    def footprint(self) -> int: ...

class CoreHierarchy:
    @staticmethod
    def build(
        graph: Graph,
        keep: Sequence[int],
        max_degree: float = ...,
        max_settled: int = ...,
        max_hops: int = ...,
        progress: Optional[Progress] = ...,
    ) -> CoreHierarchy: ...
    @property
    def core(self) -> Graph: ...
    @property
    def num_core(self) -> int: ...
    @property
    def num_retired(self) -> int: ...
    @property
    def num_arcs(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    def is_core(self, node: int) -> bool: ...

class ContractionHierarchy:
    @staticmethod
    def edge_difference(
        graph: Graph,
        deleted_neighbours: bool = ...,
        max_settled: int = ...,
        max_hops: int = ...,
        progress: Optional[Progress] = ...,
    ) -> ContractionHierarchy: ...
    @staticmethod
    def random(
        graph: Graph,
        seed: int = ...,
        max_settled: int = ...,
        max_hops: int = ...,
        progress: Optional[Progress] = ...,
    ) -> ContractionHierarchy: ...
    @property
    def num_shortcuts(self) -> int: ...
    @property
    def num_arcs(self) -> int: ...
    @property
    def footprint(self) -> int: ...
    @property
    def ranks(self) -> List[int]: ...
    def query(
        self, sources: Sequence[Tuple[int, int]], target: int
    ) -> MeetingSearch: ...

class MeetingSearch:
    @property
    def meeting(self) -> Optional[int]: ...
    @property
    def settled(self) -> int: ...
    @property
    def halves(self) -> Tuple[List[int], List[int]]: ...
    def cost(self, node: int) -> Optional[int]: ...
    def path(self, node: int) -> Optional[List[int]]: ...
    def edge_path(self, node: int) -> Optional[List[int]]: ...
    def branches(self) -> List[Tuple[int, int, int, int, List[int]]]: ...

class Heuristic:
    @staticmethod
    def zero() -> Heuristic: ...
    @staticmethod
    def euclidean(
        xs: Sequence[float], ys: Sequence[float], cost_per_distance: float
    ) -> Heuristic: ...
    @staticmethod
    def landmarks(
        graph: Graph,
        count: int,
        selection: str = ...,
        seed: int = ...,
        progress: Optional[Progress] = ...,
    ) -> Heuristic: ...
    @property
    def coverage(self) -> Optional[int]: ...
    @property
    def footprint(self) -> int: ...
    def estimate(self, node: int, target: int) -> int: ...

class OsmNetwork:
    @property
    def num_nodes(self) -> int: ...
    @property
    def num_edges(self) -> int: ...
    @property
    def node_ids(self) -> List[int]: ...
    @property
    def bounds(self) -> Tuple[float, float, float, float]: ...
    def edges(self) -> List[Tuple[int, int, int]]: ...
    def projected(self) -> Tuple[List[float], List[float]]: ...
    def coordinates(self) -> Tuple[List[float], List[float]]: ...
    def geometry(self, edge: int) -> List[Tuple[float, float]]: ...
    def windows(self) -> List[Tuple[int, List[Tuple[int, int]]]]: ...
    @property
    def unreadable_schedules(self) -> int: ...
    def nearest(
        self, lat: float, lon: float, within: Optional[Sequence[int]] = ...
    ) -> Optional[int]: ...

class SearchResult:
    @property
    def costs(self) -> List[Optional[int]]: ...
    @property
    def order(self) -> List[int]: ...
    @property
    def settled(self) -> int: ...
    def cost(self, node: int) -> Optional[int]: ...
    def path(self, node: int) -> Optional[List[int]]: ...
    def edge_path(self, node: int) -> Optional[List[int]]: ...
    def parent(self, node: int) -> Optional[int]: ...
    def parent_edge(self, node: int) -> Optional[int]: ...
    def reached(self) -> List[int]: ...
    def tree(self, graph: Graph, magnitude: str = ...) -> SearchTree: ...

class SearchTree:
    @property
    def tails(self) -> List[int]: ...
    @property
    def heads(self) -> List[int]: ...
    @property
    def edges(self) -> List[int]: ...
    @property
    def magnitudes(self) -> List[int]: ...
    @property
    def peak(self) -> int: ...
    def __len__(self) -> int: ...

def astar(
    graph: Graph,
    sources: Sequence[Tuple[int, int]],
    target: int,
    heuristic: Heuristic,
    *,
    max_cost: Optional[int] = ...,
) -> SearchResult: ...
def load_gtfs(path: str, year: int, month: int, day: int) -> Feed: ...
def load_osm(
    path: str,
    speeds: Sequence[Tuple[str, float]],
    *,
    respect_oneway: bool = ...,
    use_maxspeed: bool = ...,
    access_keys: Sequence[str] = ...,
) -> OsmNetwork: ...
def time_dependent_dijkstra(
    graph: Graph,
    calendar: Calendar,
    sources: Sequence[Tuple[int, int]],
    departing: int,
    *,
    waiting: str = ...,
    targets: Optional[Sequence[int]] = ...,
    max_cost: Optional[int] = ...,
) -> SearchResult: ...
def dijkstra(
    graph: Graph,
    sources: Sequence[Tuple[int, int]],
    *,
    targets: Optional[Sequence[int]] = ...,
    max_cost: Optional[int] = ...,
) -> SearchResult: ...
def bfs(
    graph: Graph,
    sources: Sequence[int],
    *,
    targets: Optional[Sequence[int]] = ...,
    max_depth: Optional[int] = ...,
) -> SearchResult: ...
